import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsObject } from 'class-validator';
import type { MarketingAssetPack } from '../../store/store';

export class AttachPackDto {
  @ApiProperty({
    type: 'object',
    additionalProperties: true,
    description:
      'Completed MarketingAssetPack generated by the operator from the hitlPrompt',
    example: {
      packId: 'uuid',
      listingId: 'uuid',
      generatedAt: '2026-02-27T00:00:00Z',
      seoTitle: {
        tr: 'Antalya Konyaaltı 2+1 Daire',
        en: 'Antalya Konyaaltı 2+1 Apartment',
      },
      metaDescription: { tr: '...', en: '...' },
      socialCaptions: ['caption1', 'caption2', 'caption3'],
      whatsappBroadcast: '...',
      hashtags: ['#Antalya', '#Konyaaltı', '#Emlak', '#Daire', '#SatılıkDaire'],
    },
  })
  @IsObject()
  @IsNotEmpty()
  result: MarketingAssetPack;
}
