/**
 * Static Antalya province administrative data.
 * Source: Turkish postal / administrative boundaries.
 * Update manually if new districts or neighbourhoods are added.
 */

export const DISTRICTS: string[] = [
  "Muratpaşa",
  "Kepez",
  "Konyaaltı",
  "Döşemealtı",
  "Aksu",
  "Alanya",
  "Manavgat",
  "Serik",
  "Kemer",
  "Kumluca",
  "Finike",
  "Kaş",
  "Demre",
  "Elmalı",
  "Korkuteli",
  "Akseki",
  "Gündoğmuş",
  "İbradı",
  "Gazipaşa",
];

/**
 * District → neighbourhood names (mahalles).
 * Covers the most populated districts with full lists;
 * smaller districts have representative entries.
 */
export const NEIGHBORHOODS: Record<string, string[]> = {
  Muratpaşa: [
    "Bahçelievler",
    "Balbey",
    "Barbaros",
    "Çağlayan",
    "Çakırlar",
    "Çallı",
    "Demircikara",
    "Dutlubahçe",
    "Ermenek",
    "Fener",
    "Gebizli",
    "Gözde",
    "Güllük",
    "Güzeloba",
    "Haşimişcan",
    "Kışla",
    "Kızılarık",
    "Kızıltoprak",
    "Kocatepe",
    "Kollu",
    "Konyaaltı",
    "Lara",
    "Memurevleri",
    "Mehmetçik",
    "Meltem",
    "Özgürlük",
    "Sinan",
    "Soğuksu",
    "Şirinyalı",
    "Uncalı",
    "Varsak",
    "Yenigün",
    "Yeşilbahçe",
    "Zerdalilik",
  ],
  Kepez: [
    "Altınyıldız",
    "Askeriye",
    "Atatürk",
    "Aydınlıkevler",
    "Bağlar",
    "Beymelek",
    "Cumhuriyet",
    "Doyran",
    "Emek",
    "Erler",
    "Fatih",
    "Göksu",
    "Güneş",
    "Güvenlik",
    "Hacet",
    "Huzur",
    "Işıklar",
    "Karaçay",
    "Kazım Karabekir",
    "Kuzeyyaka",
    "Manavgat",
    "Menderes",
    "Mevlana",
    "Mollalar",
    "Pınarlı",
    "Santral",
    "Sarısu",
    "Sütçüler",
    "Şahinler",
    "Teomanpaşa",
    "Toy",
    "Uncalı",
    "Varsak Karalar",
    "Varsak",
    "Yıldırım",
    "Zafer",
  ],
  Konyaaltı: [
    "Arapsuyu",
    "Archaeologia",
    "Askeriye",
    "Atatürk",
    "Bahçeyaka",
    "Çakırlar",
    "Çıplaklı",
    "Doyran",
    "Gürsu",
    "Hacıveyiszade",
    "Hurma",
    "Konyaaltı",
    "Liman",
    "Sarısu",
    "Siteler",
    "Solak",
    "Tekirova",
    "Uncalı",
    "Yeşilbayır",
  ],
  Döşemealtı: [
    "Altınkaya",
    "Aşağıkaraman",
    "Bağlıca",
    "Doğanköy",
    "Düzlerçamı",
    "Gebiz",
    "Göçerler",
    "Kepezaltı",
    "Kırkgöz",
    "Pınarkent",
    "Sarısu",
    "Yazırkent",
    "Yeşilköy",
  ],
  Aksu: [
    "Atatürk",
    "Boğazkent",
    "Çolaklı",
    "Düden",
    "Gökçeler",
    "Güzelyurt",
    "Kadriye",
    "Kavacık",
    "Kundu",
    "Kurşunlu",
    "Taşağıl",
    "Yeşilköy",
  ],
  Alanya: [
    "Alanya Merkez",
    "Avsallar",
    "Cikcilli",
    "Dim",
    "Elikesik",
    "Gazipaşa",
    "Güllerpınarı",
    "Hacet",
    "İncekum",
    "Kargıcak",
    "Kestel",
    "Konaklar",
    "Mahmutlar",
    "Obagöl",
    "Oba",
    "Payallar",
    "Sapadere",
    "Tosmur",
    "Türkler",
  ],
  Manavgat: [
    "Bucakdere",
    "Çenger",
    "Çolaklı",
    "Evrenseki",
    "Gündoğdu",
    "Kadriye",
    "Kumköy",
    "Manavgat Merkez",
    "Sarılar",
    "Side",
    "Sorgun",
    "Titreyengöl",
  ],
  Serik: [
    "Acısu",
    "Belek",
    "Boğazkent",
    "Gebiz",
    "Kadriye",
    "Serik Merkez",
    "Taşağıl",
    "Üçkuyular",
  ],
  Kemer: [
    "Beldibi",
    "Camyuva",
    "Çamyuva",
    "Göynük",
    "Kemer Merkez",
    "Kiriş",
    "Tekirova",
  ],
  Kumluca: ["Adrasan", "Finike", "Karaöz", "Kumluca Merkez", "Mavikent", "Sahilkent"],
  Finike: ["Finike Merkez", "Karaöz", "Limyra", "Turunçova"],
  Kaş: ["Bayındır", "Kalkan", "Kaş Merkez", "Kınık", "Patara"],
  Demre: ["Demre Merkez", "Kale", "Myra", "Sülüklü", "Üçağız"],
  Elmalı: ["Elmalı Merkez", "Gödene", "Kızılcadağ", "Ovacık", "Yeşilgöl"],
  Korkuteli: ["Çığlık", "Korkuteli Merkez", "Sarıkavak", "Yazır"],
  Akseki: ["Akseki Merkez", "Çimi", "İbradı yolu"],
  Gündoğmuş: ["Gündoğmuş Merkez"],
  İbradı: ["İbradı Merkez"],
  Gazipaşa: ["Gazipaşa Merkez", "Kaledran", "Konakpınar"],
};
