/**
 * Static Antalya province administrative data.
 * Source: Turkish postal / administrative boundaries.
 * Update manually if new districts or neighbourhoods are added.
 */

export const DISTRICTS: string[] = [
  "Muratpaşa",
  "Kepez",
  "Konyaaltı",
  "Döşemealtı",
  "Aksu",
  "Alanya",
  "Manavgat",
  "Serik",
  "Kemer",
  "Kumluca",
  "Finike",
  "Kaş",
  "Demre",
  "Elmalı",
  "Korkuteli",
  "Akseki",
  "Gündoğmuş",
  "İbradı",
  "Gazipaşa",
];

/**
 * District → neighbourhood names (mahalles).
 * Covers the most populated districts with full lists;
 * smaller districts have representative entries.
 */
export const NEIGHBORHOODS: Record<string, string[]> = {
  Muratpaşa: [
    "Altındağ", "Bahçelievler", "Balbey", "Barbaros", "Bayındır",
    "Cumhuriyet", "Çağlayan", "Çaybaşı", "Demircikara", "Deniz",
    "Doğuyaka", "Dutlubahçe", "Elmalı", "Ermenek", "Etiler",
    "Fener", "Gebizli", "Gençlik", "Güvenlik", "Güzelbağ",
    "Güzeloba", "Güzeloluk", "Haşimişcan", "Kılınçarslan", "Kırcami",
    "Kışla", "Kızılarık", "Kızılsaray", "Kızıltoprak", "Konuksever",
    "Mehmetçik", "Meltem", "Memurevleri", "Meydankavağı", "Muratpaşa",
    "Sedir", "Selçuk", "Sinan", "Soğuksu", "Şirinyalı",
    "Tahılpazarı", "Tarım", "Topçular", "Tuzcular", "Üçgen",
    "Varlık", "Yenigöl", "Yenigün", "Yeşilbahçe", "Yeşildere",
    "Yeşilova", "Yıldız", "Yüksekalan", "Zerdalilik", "Zümrütova",
  ],
  Kepez: [
    "Ahatlı", "Akpınar", "Altıayak", "Altınova Düden", "Altınova Orta",
    "Altınova Sinan", "Atatürk", "Avni Tolunay", "Ayanoğlu", "Aydoğmuş",
    "Baraj", "Barış", "Başköy", "Beşyol", "Çamlıbel", "Çamlıca",
    "Çankaya", "Demirel", "Duacı", "Duraliler", "Düden", "Emek",
    "Erenköy", "Esentepe", "Fabrikalar", "Fatih", "Fevzi Çakmak",
    "Gazi", "Göçerler", "Gökpınar", "Gülveren", "Gündoğdu", "Güneş",
    "Habibler", "Hüsnü Karakaş", "İn Yavuz Selim", "Kanal", "Karşıyaka",
    "Kazım Karabekir", "Kepez", "Kirişçiler", "Korkuteli", "Kültür",
    "Kütükçü", "Menderes", "Merkez Köy", "Metin Çakas", "Metin Kasapoğlu", "Mehmet Akif Ersoy",
    "Odabaşı", "Özgürlük", "Santral", "Sütçüler", "Şafak", "Şelale",
    "Teomanpaşa", "Toki", "Ulus", "Ünsal", "Varak", "Yavuz Selim",
    "Yeni", "Yeni Doğan", "Yeni Emek", "Yeni Mahalle", "Yeşiltepe",
    "Yeşilyurt", "Yükseliş", "Zeytinlik",
  ],
  Konyaaltı: [
    "Arapsuyu",
    "Archaeologia",
    "Askeriye",
    "Atatürk",
    "Bahçeyaka",
    "Çakırlar",
    "Çıplaklı",
    "Doyran",
    "Gürsu",
    "Hacıveyiszade",
    "Hurma",
    "Konyaaltı",
    "Liman",
    "Sarısu",
    "Siteler",
    "Solak",
    "Tekirova",
    "Uncalı",
    "Yeşilbayır",
  ],
  Döşemealtı: [
    "Altınkaya",
    "Aşağıkaraman",
    "Bağlıca",
    "Doğanköy",
    "Düzlerçamı",
    "Gebiz",
    "Göçerler",
    "Kepezaltı",
    "Kırkgöz",
    "Pınarkent",
    "Sarısu",
    "Yazırkent",
    "Yeşilköy",
  ],
  Aksu: [
    "Atatürk",
    "Boğazkent",
    "Çolaklı",
    "Düden",
    "Gökçeler",
    "Güzelyurt",
    "Kadriye",
    "Kavacık",
    "Kundu",
    "Kurşunlu",
    "Taşağıl",
    "Yeşilköy",
  ],
  Alanya: [
    "Alanya Merkez",
    "Avsallar",
    "Cikcilli",
    "Dim",
    "Elikesik",
    "Gazipaşa",
    "Güllerpınarı",
    "Hacet",
    "İncekum",
    "Kargıcak",
    "Kestel",
    "Konaklar",
    "Mahmutlar",
    "Obagöl",
    "Oba",
    "Payallar",
    "Sapadere",
    "Tosmur",
    "Türkler",
  ],
  Manavgat: [
    "Bucakdere",
    "Çenger",
    "Çolaklı",
    "Evrenseki",
    "Gündoğdu",
    "Kadriye",
    "Kumköy",
    "Manavgat Merkez",
    "Sarılar",
    "Side",
    "Sorgun",
    "Titreyengöl",
  ],
  Serik: [
    "Acısu",
    "Belek",
    "Boğazkent",
    "Gebiz",
    "Kadriye",
    "Serik Merkez",
    "Taşağıl",
    "Üçkuyular",
  ],
  Kemer: [
    "Beldibi",
    "Camyuva",
    "Çamyuva",
    "Göynük",
    "Kemer Merkez",
    "Kiriş",
    "Tekirova",
  ],
  Kumluca: ["Adrasan", "Finike", "Karaöz", "Kumluca Merkez", "Mavikent", "Sahilkent"],
  Finike: ["Finike Merkez", "Karaöz", "Limyra", "Turunçova"],
  Kaş: ["Bayındır", "Kalkan", "Kaş Merkez", "Kınık", "Patara"],
  Demre: ["Demre Merkez", "Kale", "Myra", "Sülüklü", "Üçağız"],
  Elmalı: ["Elmalı Merkez", "Gödene", "Kızılcadağ", "Ovacık", "Yeşilgöl"],
  Korkuteli: ["Çığlık", "Korkuteli Merkez", "Sarıkavak", "Yazır"],
  Akseki: ["Akseki Merkez", "Çimi", "İbradı yolu"],
  Gündoğmuş: ["Gündoğmuş Merkez"],
  İbradı: ["İbradı Merkez"],
  Gazipaşa: ["Gazipaşa Merkez", "Kaledran", "Konakpınar"],
};
